on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@v5
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        accessToken: api-433455d8-0785-4cea-abf0-c7ba484348c2
        projKey: default
